### ISSUE TITLE
Remove Overflow along X Axis.

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#104]
Remove Overflow along X Axis in Contribution page
Resolution: Mobile
Component: contribution
Redirect: /contribution

![image](https://user-images.githubusercontent.com/32712438/95012812-2a82c000-0659-11eb-83e6-ba50983e4b95.png)

**Comment by karma200020** [comment]
Can I work on this?

**Comment by goliakshay357** [comment]
Sure @karma200020 👍
