### ISSUE TITLE
Alert for verifying email ID

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#108]
![image](https://user-images.githubusercontent.com/32712438/95418094-556c5d00-0954-11eb-8f61-25b97f16c5cb.png)
Alert for verifying email ID while login

**Comment by danielochka** [comment]
Can you tell me more info about it?

**Comment by goliakshay357** [comment]
Hi @danielochka ,
When a user signs up for the first time. He needs to verify his email (A mail will be sent to that email ID) before he makes a login. 
This is the JSON given from backend when the user did not verify his email ID.

Issue: 
Whenever this JSON is coming... A alert has to be given to the user to verify his email so he can login. This is something like Verify email address popup.

**Comment by matheusmosca** [comment]
Hi, I'd like to solve it. Could you assign it to me?
