### ISSUE TITLE
Toolbox is default by display block.

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#114]
Toolbox is default by display block when you add the block

**Comment by goliakshay357** [comment]
![image](https://user-images.githubusercontent.com/32712438/95451381-54075880-0985-11eb-9b0e-52781ca17665.png)
![image](https://user-images.githubusercontent.com/32712438/95451431-62ee0b00-0985-11eb-8738-0ac61a82df1f.png)

**Comment by saidhanush1212** [comment]
@goliakshay357 Can I solve this issue

**Comment by goliakshay357** [comment]
Sure :+1:
