### ISSUE TITLE
Add canvasboard logo

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#116]
Add canvasboard logo beside the title in navbar
![image](https://user-images.githubusercontent.com/32712438/95452129-6d5cd480-0986-11eb-9fea-71c6f2ad2b9b.png)

**Comment by matheusmosca** [comment]
Hey, can I work on this one? :smile_cat::

**Comment by goliakshay357** [comment]
@matheusmosca Sure :+1:

**Comment by goliakshay357** [comment]
![image](https://user-images.githubusercontent.com/32712438/95458567-f4627a80-098f-11eb-84fd-8e0880cc237c.png)
Something like this

**Comment by matheusmosca** [comment]
Ok! I'll probably send a PR at the end of the day.
