### ISSUE TITLE
Right align the text inside the cards

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#119]
Center align the text inside the cards

**Comment by alexandramj92** [comment]
I am interested. Can you assign me to this issue? Thanks!

**Comment by goliakshay357** [comment]
Hi @alexandramj92 , Sure :+1:

**Comment by goliakshay357** [comment]
@alexandramj92 , 
This is a plugin based issue... 
1) Add the functionality button in toolbox.
2) Create the required class and export it to new-board component

Please feel free to join our IRC channel for further communication. 
Thanks

**Comment by goliakshay357** [comment]
@alexandramj92 are you working on this issue?
