### ISSUE TITLE
Clear Background not working in Board Component

### ISSUE THREAD

**Issue by kingavatar** [Canvasbird/canvasboard#172]
**Describe the bug** 🐛 
In Board Component clear background is not working
**To Reproduce**
 1. Go to 'board'
 2. Click on 'graph background'
 3. Click on 'white background'

**Observed behavior**
A clear and concise description of what you have observed.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information; delete this section if the issue does not arise on desktop):**

**Smartphone (please complete the following information; delete this section if the issue does not arise on smartphones):**

**Additional context**

**Comment by himeshkrishnaosuri** [comment]
I will fix this

**Comment by kingavatar** [comment]
Sure i will assign it to you.
