### ISSUE TITLE
Sign up and login form are compressed by reducing screen width

### ISSUE THREAD

**Issue by matheusmosca** [Canvasbird/canvasboard#182]
**Describe the bug** 🐛 
The sign-up/sign-in form is compressed in a specific width

**To Reproduce**
 1. Go to '/login' or '/sign-up'
 2. Reduce the width resolution slowly and see the error

**Observed behavior**
A clear and concise description of what you have observed.

**Expected behavior**

**Screenshots**

![bug](https://user-images.githubusercontent.com/42419282/97920145-c7f41100-1d37-11eb-85e1-0e0466202b83.gif)

***
**Desktop (please complete the following information; delete this section if the issue does not arise on desktop):**
 - OS: Ubuntu 18.04
 - Browser Firefox 82.2

**Additional context**

**Comment by Amit366** [comment]
Sir I would like to solve this issue.

**Comment by sakshikhachane** [comment]
@goliakshay357 I would take on this issue. Please assign me this issue.

**Comment by goliakshay357** [comment]
Sure!

**Comment by sakshikhachane** [comment]
@goliakshay357 I have adjusted the screen. 
![Canvasboard - Google Chrome 01-01-2021 15_21_49](https://user-images.githubusercontent.com/53635792/103436758-44767380-4c45-11eb-8f2d-39c51aa84b4f.png)
![Canvasboard - Google Chrome 01-01-2021 15_21_43](https://user-images.githubusercontent.com/53635792/103436760-46403700-4c45-11eb-9d34-2b72cef441cf.png)
![Canvasboard - Google Chrome 01-01-2021 15_21_36](https://user-images.githubusercontent.com/53635792/103436761-47716400-4c45-11eb-81e3-fe9299b6d803.png)

**Comment by goliakshay357** [comment]
Hey, 
This looks cool. Please submit a PR for the review! 

Thanks

**Comment by sakshikhachane** [comment]
@goliakshay357 Is it done? Sorry for the delay in response because of the exams.

**Comment by goliakshay357** [comment]
@sakshikhachane, 
This issues seems like it's not solved. Reopened it again. 

Take your own time, no hurries!
Thanks

**Comment by goliakshay357** [comment]
is this issue resolved? 
@Kajol-Kumari @sakshikhachane?
