### ISSUE TITLE
Unauthenticated users are able to access authenticated routes

### ISSUE THREAD

**Issue by matheusmosca** [Canvasbird/canvasboard#183]
**Describe the bug** 🐛 
Unauthenticated users are able to access authenticated routes such as '/dashboard' and '/files'

**Desktop (please complete the following information; delete this section if the issue does not arise on desktop):**
 - OS: Ubuntu 18.04
 - Browser Firefox 82.2

**Additional context**

**Comment by IshanManchanda** [comment]
I'd like to work on this

**Comment by goliakshay357** [comment]
Hello @IshanManchanda ,
This seems to be solved. Can you please look into other issues? 

Thanks.
