### ISSUE TITLE
save and exit buttons are overlapping the sidebar

### ISSUE THREAD

**Issue by matheusmosca** [Canvasbird/canvasboard#184]
**Describe the bug** 🐛 
The save and exit buttons are overlapping the sidebar menu.

**To Reproduce**
 1. Go to '/board'
 2. See the error in the sidebar

**Screenshots**
![Screenshot_2020-11-02 Canvasboard](https://user-images.githubusercontent.com/42419282/97922631-8cf3dc80-1d3b-11eb-8e6b-8e4850465dcd.png)

***

**Desktop1
 - OS: Ubuntu 18.04
 - Browser Firefox 82.2
 - Resolution 1366 x 768

**Desktop2
 - OS Windows 10
 - Browser Firefox
 - Resolution 1920 x 1080

**Additional context**
This bug appears in both of my notebooks.

**Comment by DevoAbhi** [comment]
I have worked on this issue. 
Please see the attached screenshot for the same.
<img width="960" alt="cavasboard_buttons_alligned" src="https://user-images.githubusercontent.com/54373853/99507843-e863d280-29a9-11eb-9863-f639d651139d.PNG">
