### ISSUE TITLE
Wrong autofill in sign up page

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#186]
**Describe the bug** 🐛 
![image](https://user-images.githubusercontent.com/32712438/97950704-cff69400-1dbd-11eb-812e-11a33dbf0da5.png)
Wrong autofill in sign up page

**Comment by DevoAbhi** [comment]
@goliakshay357 I think this issue is already solved in the PR - #225. 
Thank you.

**Comment by goliakshay357** [comment]
Yes
Thanks for the notice🙂

**Comment by DevoAbhi** [comment]
Thank you,
