### ISSUE TITLE
Rename workspace

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#204]
functionality to Rename the workspace(folder) in the dashboard. 

If the user wants to change the name of the workspace, then the user can click on the rename functionality to do it.
location: /dashboard
![image](https://user-images.githubusercontent.com/32712438/99515520-11d52c00-29b3-11eb-92b2-45d899920e14.png)

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @goliakshay357

**Comment by Kajol-Kumari** [comment]
Fixed via [this](https://github.com/Canvasbird/canvasboard/pull/249) PR
