### ISSUE TITLE
Adding H1, H2, H3 tags

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#21]
Flexibility for the user to make use of H1 H2 and H3 tags on creative board

**Comment by goliakshay357** [comment]
Changing the toolbox from static to dynamic

**Comment by goliakshay357** [comment]
Resolved via [this](https://github.com/Canvasbird/canvasboard/commit/0979088d0af51de425ec3f52ef03ca711ea42e45) commit

**Comment by Kajol-Kumari** [comment]
Hey @goliakshay357, the `h1, h2 and h3` tag is working fine. But how do I get a paragraph in the creative-board back again?

**Comment by goliakshay357** [comment]
Will solve it in my follow-up commit.
Thanks.
