### ISSUE TITLE
Add a confirmation box on click of exit button.

### ISSUE THREAD

**Issue by DevoAbhi** [Canvasbird/canvasboard#215]
**Is your feature request related to a problem? Please describe.**
If the user clicks the exit button in the board component, it navigates to the previous route even if the user has unsaved data present.

**Describe the solution you'd like** 💡
A solution for this can be a confirmation box that appears after clicking the exit button if the user has some unsaved data. If user has no unsaved data, the user should directly be navigated to the previous route without any confirmation box.

**Additional context*
Go to the board component and click exit button and observe the changes.

**Comment by DevoAbhi** [comment]
I would like to work on this issue.

**Comment by goliakshay357** [comment]
Hello @DevoAbhi , 
The BoardComponent [i.e version1 board] is now adapted to the creative board as a plugin. 

Thanks.

**Comment by DevoAbhi** [comment]
@goliakshay357 Great! Noted.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @goliakshay357
