### ISSUE TITLE
Functionality to rename folder name

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#219]
**Is your feature request related to a problem? Please describe.**
Rename folder 

**Describe the solution you'd like** 💡
Call the rename API to rename the folder

location: /dashboard

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @goliakshay357

**Comment by MegaMind77-coder** [comment]
Hello! 
Do we need to change the board title or only the folder name ?

**Comment by MegaMind77-coder** [comment]
@goliakshay357 is issue number #204 the same? 

Renaming the folder would be the same as renaming the workspace right?
