### ISSUE TITLE
Logout in mobile resolution

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#220]
**Describe the bug** 🐛 
- [ ] Logout button should be inside the navigation bar in mobile resolution.
- [ ] Change logout from Button to li
![image](https://user-images.githubusercontent.com/32712438/99933763-f8046200-2d81-11eb-9988-524fde62cf95.png)
![image](https://user-images.githubusercontent.com/32712438/99933817-1bc7a800-2d82-11eb-8d8a-d5e93000b1df.png)

**Comment by DevoAbhi** [comment]
Can I work on this issue?
