### ISSUE TITLE
Navigate to Dashboard if AUTH token is not expired

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#221]
**Describe the bug** 🐛 
Direct Navigate to Dashboard if user AUTH token is not expired

**Comment by matheusmosca** [comment]
I would like to solve this issue! Could you assign it to me?

**Comment by goliakshay357** [comment]
Sure!

**Comment by IshanManchanda** [comment]
@goliakshay357 I'd like to work on this.

**Comment by goliakshay357** [comment]
Hello @IshanManchanda,
Thanks for your interest. Looking forward to your contribution :smile: .

**Comment by IshanManchanda** [comment]
@goliakshay357 I'm assuming routes 'home', 'login', and 'sign-up' should redirect to dashboard, is that right?

**Comment by goliakshay357** [comment]
Yes
