### ISSUE TITLE
Add scroll animations to specific sections

### ISSUE THREAD

**Issue by m-code12** [Canvasbird/canvasboard#233]
**Is your feature request related to a problem? Please describe.**
It would be better if we could add scroll animations to the block based editing,type and draw and custom plugins sections to keep our users engaged with our content. Animations will be used to focus users attention on what's important and will also show the flow of our website. 

**Describe the solution you'd like** 💡
I would like to use JQuery or css animations to pull this off.

**Comment by arbazkhan56** [comment]
Can you Assign me?

**Comment by m-code12** [comment]
@Kajol-Kumari Could you assign me this issue so that I can start working on it? It's been 12 days since I have opened it.

**Comment by Kajol-Kumari** [comment]
Hey @m-code12 Please go ahead with this issue.
@arbazkhan56 Please look for any other open issue :)

**Comment by m-code12** [comment]
@Kajol-Kumari Please assign me points for opening this issue as a part of nwoc.

**Comment by m-code12** [comment]
@Kajol-Kumari I am not that familiar with the frontend tech stack used for this project, I tried doing it but it isn't working.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I am not that familiar with the frontend tech stack used for this project, I tried doing it but it isn't working. Maybe I can connect with you on slack regarding this or maybe you can assign someone else.

Either way works for me, if you want to go ahead with that issue, ping me on slack and you want to go ahead with this only, please remove your assignment from that issue :)
