### ISSUE TITLE
Files CRUD

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#234]
**Location:** Inside workspace [ folder/:id ]

**Tasks:**
1. Get all the files of a specific workspace from backend API and display it on frontend
2. Create a new file inside a workspace
3. Delete a file 
4. Rename a file

**Comment by MegaMind77-coder** [comment]
@goliakshay357  could you pls explain the tasks a bit more ?

**Comment by goliakshay357** [comment]
Hey @MegaMind77-coder, 
This issue is being solved by others, Can you please choose another one? 

Thanks

**Comment by MegaMind77-coder** [comment]
Sure!
