### ISSUE TITLE
Make toolbox responsive

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#24]
Make toolbox responsive on screens

**Comment by DevoAbhi** [comment]
I want to work on this issue. Can I be assigned?

**Comment by goliakshay357** [comment]
Yeah sure! 
Please go ahead.

**Comment by goliakshay357** [comment]
@DevoAbhi ,
Want to work on this issue?

**Comment by DevoAbhi** [comment]
Yes, sure!
