### ISSUE TITLE
Rename CSS background 

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#241]
Problem: When pressed edit... background color is white.
![image](https://user-images.githubusercontent.com/32712438/101842801-d91e1200-3b6e-11eb-96db-f11e50d85122.png)

Requirement: Make the background transparent.

**Comment by Kajol-Kumari** [comment]
Closing via [this](https://github.com/Canvasbird/canvasboard/pull/237) PR
