### ISSUE TITLE
Contributors Image In Readme

### ISSUE THREAD

**Issue by Vishal-raj-1** [Canvasbird/canvasboard#251]
I think it is a great feature to add contributors image in README file. It really motivate to contributors. It is dynamically order the contributors. 

![contrimga](https://user-images.githubusercontent.com/59874304/102012505-dd198200-3d70-11eb-8e1e-379f47ccd7e2.JPG)

If you want to this feature on README so I want to do this issue  !! 😄

**Comment by Kajol-Kumari** [comment]
Hey @Vishal-raj-1 Thanks for proposing this idea. Please go ahead with this issue, just make sure that the images are linked with the contributors github profile.

Happy Coding :)

**Comment by Vishal-raj-1** [comment]
> Hey @Vishal-raj-1 Thanks for proposing this idea. Currently we are using a bot for this. Please go ahead with this issue, just make sure that the images are linked with the contributors github profile.

Sure
