### ISSUE TITLE
Image Slider in Home Page

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#255]
![image](https://user-images.githubusercontent.com/32712438/102030306-484a6f00-3dd8-11eb-944c-ba6ab5df84fd.png)

Automatic Image slider in home page: 
**Images Link:**
Image1: src/assets/home/blocks.png
Image2: src/assets/home/slider_img2.png
Image3: src/assets/home/slider_img3.png

**Comment by Vishal-raj-1** [comment]
I want to work on this issue @goliakshay357 Sir could you please assign this issue to me!!

**Comment by goliakshay357** [comment]
Sure @Vishal-raj-1 :+1:

**Comment by sakshikhachane** [comment]
@goliakshay357  I would like to work on this issue. I am a participant in DWOC.

**Comment by goliakshay357** [comment]
Sure! Go ahead.

**Comment by sakshikhachane** [comment]
@goliakshay357 Please review the PR.

**Comment by goliakshay357** [comment]
Hey @sakshikhachane,
Given review. Please checkout! 
Thanks

**Comment by sakshikhachane** [comment]
@goliakshay357 Please add level to this else it won't get counted.

**Comment by goliakshay357** [comment]
Sure, @saidhanush1212
Thanks for the notice!
