### ISSUE TITLE
Adding contributors on website

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#256]
Adding contributors on /contribution page
**Demo:**
![image](https://user-images.githubusercontent.com/32712438/102031129-040c9e00-3ddb-11eb-8b24-233db8d23193.png)

**Comment by urvashi-code1255** [comment]
@goliakshay357 Sir, I want to contribute to this issue. Please assign it to me.

**Comment by Kajol-Kumari** [comment]
> @goliakshay357 Sir, I want to contribute to this issue. Please assign it to me.

Hey @urvashi-code1255 please go ahead with this issue.Looking forward to your PR

**Comment by Kajol-Kumari** [comment]
Hey @urvashi-code1255 can you please let us know if you are still working on this issue?

**Comment by urvashi-code1255** [comment]
Yes mam. I am working on it.
