### ISSUE TITLE
Add NWOC, KWOC & SWOC In README.

### ISSUE THREAD

**Issue by Vishal-raj-1** [Canvasbird/canvasboard#258]
This project is participating Open Source Program(NWOC, KWOC, and SWOC). This should be show in README.

**Comment by goliakshay357** [comment]
+[WOC](https://winterofcode.com/) :100: 
Thanks for the suggestions. Please go ahead if you want to update the README.md

**Comment by Vishal-raj-1** [comment]
> +[WOC](https://winterofcode.com/) 💯
> Thanks for the suggestions. Please go ahead if you want to update the README.md

Sure !!
