### ISSUE TITLE
Ctrl+Z on the whiteBoard or an undo feature

### ISSUE THREAD

**Issue by MegaMind77-coder** [Canvasbird/canvasboard#260]
**Is your feature request related to a problem? Please describe.**
Undo Feature for WhiteBoard using Ctrl+Z or a Button.

**Describe the solution you'd like** 💡
Make Ctrl+z functional for keypad users in case they end up making a mistake while writing on the whiteboard.
An Undo Button for stylus users.

**Comment by Kajol-Kumari** [comment]
Thanks for introducing this idea @MegaMind77-coder . Would you like to go ahead with this issue?

**Comment by MegaMind77-coder** [comment]
Not Yet
I am still figuring it out. 
I would be willing to discuss it here.

**Comment by MegaMind77-coder** [comment]
Pls, assign a Label to this issue.

**Comment by Piyush3436** [comment]
@Kajol-Kumari, I'll work on this. Please assign this to me.

**Comment by GaganAgarwal77** [comment]
I have made a pr regarding this issue, kindly review it.

**Comment by Kajol-Kumari** [comment]
Hey @MegaMind77-coder and @Piyush3436 I was a bit inactive and so missed your comments. @GaganAgarwal77 please make sure to start working on an issue only after claiming it and getting assigned. Directly coming up with a PR isn't a good practice in open source.

**Comment by GaganAgarwal77** [comment]
@Kajol-Kumari Sure I'll keep that in mind from next time👍🏽
