### ISSUE TITLE
Potential Bug Risks and Anti-Patterns

### ISSUE THREAD

**Issue by HarshCasper** [Canvasbird/canvasboard#264]
## Description 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/canvasboard/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point of time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

Some of the notable issues are: 

- Unused Variables and Functions ( [here](https://deepsource.io/gh/HarshCasper/canvasboard/issue/JS-0356/) and [here](https://deepsource.io/gh/HarshCasper/canvasboard/issue/JS-0321/occurrences) )
- Deprecated APIs [here](https://deepsource.io/gh/HarshCasper/canvasboard/issue/JS-0272/)
- Import of Private Modules [here](https://deepsource.io/gh/HarshCasper/canvasboard/issue/JS-0265/)
- Direct Usage of `Object.prototypes` builtins [here](https://deepsource.io/gh/HarshCasper/canvasboard/issue/JS-0021/occurrences)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

**Comment by MegaMind77-coder** [comment]
I think dependabot also notifies the same, don't know why the bot is sending PRs for that.

**Comment by HarshCasper** [comment]
> I think dependabot also notifies the same, don't know why the bot is not sending PRs for that.

Dependabot is a dependency version based vulnerability anaysis tool. It uses a list of vulnerabilities and the versions in which the dependencies show those dependencies to send PRs for solving the same.

DeepSource is different in that it helps you find issues in the code that come up due to developer fault, like wrong syntax, unnecessary control flow statements, messy code, etc. 

You can check out the Result Dashboard to better analyze what DeepSource does 😄

**Comment by deepak2431** [comment]
@goliakshay357 @Kajol-Kumari Please have a look at this. Let me know your views if you feel integrating this would be great for our project.
