### ISSUE TITLE
[Bug] Long Usernames going out of the screen for smaller screen

### ISSUE THREAD

**Issue by Kajol-Kumari** [Canvasbird/canvasboard#271]
**Describe the bug** 🐛 
If the user have very long user name, it's going out of the screen for large screens.

**To Reproduce**
1. Register with a very long user name
2. Visit the workspaces page

**Expected behavior**
The long names should have been reduced in the form of ellipses(...)  or line break (whichever looks better) if it's long enough

**Screenshots**
![Screenshot from 2020-12-20 22-52-41](https://user-images.githubusercontent.com/44888949/102719895-b29e6a80-4316-11eb-89d7-9743df7c1f57.png)

**Comment by OmarMorales71** [comment]
@Kajol-Kumari Can I work on this issue?

**Comment by Kajol-Kumari** [comment]
Hey @OmarMorales71 sue! 
Go ahead with this. Looking forward to your PR :)

**Comment by goliakshay357** [comment]
@OmarMorales71,
Working on this issue?

**Comment by OmarMorales71** [comment]
@goliakshay357 the PR is there

**Comment by goliakshay357** [comment]
Yes! Can you please look into the changes requested?
Thanks

**Comment by OmarMorales71** [comment]
@goliakshay357 Sure. I already solved the review.
