### ISSUE TITLE
[Bug] Long Folder name distort the folder size

### ISSUE THREAD

**Issue by Kajol-Kumari** [Canvasbird/canvasboard#272]
**Describe the bug** 🐛 
If we give very large folder name to any workspace, it's taking the space same as the folder name.

**To Reproduce**
1. go to workspaces
2. Create a workspace with a very long name

**Expected behavior**
Folder size should have been fixed and the long names should have been reduced to ellipses

**Enhancement**
As soon as user hover over `Enter` button, he/she should be shown the whole folder name

**Screenshots**
![Screenshot from 2020-12-20 23-20-20](https://user-images.githubusercontent.com/44888949/102720462-7ec54400-431a-11eb-85ec-c126c51d4ca0.png)

**Comment by GaganAgarwal77** [comment]
Can I be assigned to this issue?

**Comment by Kajol-Kumari** [comment]
Sure @GaganAgarwal77 you can go ahead with this issue. Looking forward to your PR

**Comment by GaganAgarwal77** [comment]
@Kajol-Kumari kindly check now
