### ISSUE TITLE
Showing a watermark when folders [Workspaces] are empty

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#273]
**Is your feature request related to a problem? Please describe.**
When Workspace [dashboard folders] are empty, the space is blank as shown below.
![image](https://user-images.githubusercontent.com/32712438/102916422-8bc46d80-44a9-11eb-87fe-ab811dabe745.png)
Path: /dashboard

**Describe the solution you'd like** 💡
Adding a watermark would be a better option.

**Describe alternatives you've considered**
Any design or watermark indicating the workspaces are empty.

**Comment by urvashi-code1255** [comment]
@goliakshay357 I want to work on this issue. Please assign me this.

**Comment by goliakshay357** [comment]
@DevoAbhi Did you work on this?

**Comment by DevoAbhi** [comment]
> @DevoAbhi Did you work on this?

No, I worked only on the search workspace part and if the user searches for a folder that is not present, a "No Workspace Found" message would appear.

**Comment by DevoAbhi** [comment]
> @DevoAbhi Did you work on this?

I would work on this. I would submit a PR ASAP.

**Comment by goliakshay357** [comment]
@DevoAbhi, Sure!
