### ISSUE TITLE
[Bug]No-Workspace-Found

### ISSUE THREAD

**Issue by GaganAgarwal77** [Canvasbird/canvasboard#286]
**Describe the bug** 🐛 
Currently on adding a new folder , the message of "No Workspace Found!" stays there and only goes away on a reload, Also if the dashboard has only 1 folder and we delete it, the message does not show up untill a reload.

**To Reproduce**
 1. Go to Dashboard
 2. Make sure it's empty
 2. Click on Add New Workspace
 3. See error
 4. Delete only workspace just made
 5. See error

**Observed behavior**
The message stays as the check doesn't happen until a reload.

**Expected behavior**
We can just  add a check while adding a new folder or deleting a folder , and hide or show the element based on the number of folders.

**Screenshots**
![New_Workspace_Bug](https://user-images.githubusercontent.com/53825001/103141667-82dbd200-471d-11eb-9504-30042155e4fc.png)

**Desktop (please complete the following information; delete this section if the issue does not arise on desktop):**

**Smartphone (please complete the following information; delete this section if the issue does not arise on smartphones):**

**Additional context**

**Comment by DevoAbhi** [comment]
Thank you @GaganAgarwal77 for stating this bug. 
I also found out about this bug yesterday, I will submit a PR for this shortly.

**Comment by DevoAbhi** [comment]
Thank you @GaganAgarwal77  for stating the bug.
I also found about the bug yesterday. 
@goliakshay357 @Kajol-Kumari can I be assigned for this?
I will submit a PR shortly.

**Comment by goliakshay357** [comment]
@DevoAbhi Sure!
