### ISSUE TITLE
Add colour dynamically to the folder

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#287]
**Is your feature request related to a problem? Please describe.**
The folders [Workspace] colors in the dashboard are currently static. ( i.e pink gradient )
![image](https://user-images.githubusercontent.com/32712438/103144788-71162100-4755-11eb-9d15-46d4727a9c97.png)

Would be great if the gradient color selection is of user choice while creating the folder.

**Describe the solution you'd like** 💡
When the user selects the RGB format provided while creating the workspace. The value is passed in JSON and stored in the backend.

**Comment by pranu2502** [comment]
Can I work on this issue?

**Comment by goliakshay357** [comment]
Sure! Looking forward to a PR.

Thanks

**Comment by goliakshay357** [comment]
Hey @pranu2502,
Working on this issue?

**Comment by pranu2502** [comment]
Yeah, I am waiting for you to send the colours

**Comment by goliakshay357** [comment]
![image](https://user-images.githubusercontent.com/32712438/105166838-ea7b1680-5b3d-11eb-911e-d090d83e791e.png)

**Hexcodes:**
#96F4F7 
#C1F7F7 
#ECD9E9 
#ECD9E9 
#FFBDC3
