### ISSUE TITLE
Logout action from button to dropdown

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#290]
**Is your feature request related to a problem? Please describe.**
Logout action is currently in the form of a button. 
![image](https://user-images.githubusercontent.com/32712438/103145001-0bc42f00-4759-11eb-8b49-00e30f715670.png)
![image](https://user-images.githubusercontent.com/32712438/103145007-1a124b00-4759-11eb-8232-eac67018476b.png)

Would be great if it is changed to navbar-dropdown.

**Comment by Rizwan-S** [comment]
Hey @goliakshay357! Can I work on this one?

**Comment by kingavatar** [comment]
I have assigned it to you @Rizwan-S.
