### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by m-code12** [Canvasbird/canvasboard#296]
We can add a code of conduct file in this project, whose link I need to attach in the welcome bot issue that I am working on #274 .

**Comment by goliakshay357** [comment]
Updated. 
Thanks.

**Comment by Kajol-Kumari** [comment]
Hey @m-code12 we already have a code of conduct [here](https://github.com/Canvasbird/canvasboard/blob/master/CODE_OF_CONDUCT.md). You can use this in our bot.

**Comment by m-code12** [comment]
> Hey @m-code12 we already have a code of conduct [here](https://github.com/Canvasbird/canvasboard/blob/master/CODE_OF_CONDUCT.md). You can use this link in the bot.

Alright, I'll use that, thanks!
Please assign me points for opening this issue.

**Comment by Kajol-Kumari** [comment]
Hey @m-code12 as we already had `code-of-conduct` in our codebase, so I can assign you points for this.

**Comment by m-code12** [comment]
> Hey @m-code12 as we already had `code-of-conduct` in our codebase, so I can assign you points for this.

It wasn't there previously, @goliakshay357 added it after I created this issue.

**Comment by Kajol-Kumari** [comment]
Ah, I mistaken it by contributing guidelines. Will update the point for this.
