### ISSUE TITLE
Make the plus sign active

### ISSUE THREAD

**Issue by Khimit** [Canvasbird/canvasboard#304]
Can we make this **plus sign** also **active** , so that after clicking on that user can add new workspace for him. Up till now user can only add after clicking on "**add new workspace**" tab. This can make it more user-friendly.
![canva3](https://user-images.githubusercontent.com/46605529/103200373-2fcb7000-4913-11eb-9bf7-d7f44c9233ab.PNG)

**Comment by Ak-panchal** [comment]
assign me?

**Comment by goliakshay357** [comment]
Sure!

**Comment by MegaMind77-coder** [comment]
Can I take up this issue? If it is not being worked on anymore ?

**Comment by goliakshay357** [comment]
@Ak-panchal, are you working on this issue?

**Comment by goliakshay357** [comment]
@MegaMind77-coder, 
Sorry for the delay. You can take up this issue.

Thanks
