### ISSUE TITLE
Update Contribution.md file

### ISSUE THREAD

**Issue by bhavesh1129** [Canvasbird/canvasboard#305]
Hey!
I want to rearrange your existing contributing file by adding all necessary details, guidelines, to look it more better adding some relevant images and some emojis.

Hope you like it.
Thank you!

**Comment by goliakshay357** [comment]
Sure. That would be great! 
Looking forward to a PR.
Thanks

**Comment by goliakshay357** [comment]
Hey @bhavesh1129, 
Looking forward to updates. 

Thanks
