### ISSUE TITLE
Custom error message not displayed for duplicate usernames

### ISSUE THREAD

**Issue by DevoAbhi** [Canvasbird/canvasboard#308]
**Describe the bug** 🐛 
If the user tries to signup using a username that has already been registered, then they get an error message that is not easy to follow. Thus the user might be confused about the reason for which they are being prevented from signup.

**To Reproduce**
 1. Go to Signup Page
 2. Type a username that has already been registered
 3. Type other details
 4. Click on the Signup button
 5. See error

**Observed behavior**
If the user tries to signup using a username that is already registered then they get a error message that is not easy to understand.

**Expected behavior**
The user must get a custom error message that is understandable when they signup using a duplicate username.

**Screenshots**
![canva-signup-username](https://user-images.githubusercontent.com/54373853/103231789-b22d5180-495e-11eb-9508-e523da9c0088.png)

**Desktop (please complete the following information; delete this section if the issue does not arise on desktop):**

**Smartphone (please complete the following information; delete this section if the issue does not arise on smartphones):**

**Additional context**
Please mention if any other clarification is required regarding the bug.

**Comment by Nikcodes10** [comment]
Can I work on this?
