### ISSUE TITLE
New Board Css issue

### ISSUE THREAD

**Issue by shivaamm** [Canvasbird/canvasboard#314]
In the slidermenu the toolbox(text) and close option are having some margin issue. 
Look at both the images for changes.

![1](https://user-images.githubusercontent.com/59584173/103461849-50e2f500-4d47-11eb-9384-604a5f196541.png)
![2](https://user-images.githubusercontent.com/59584173/103461850-52acb880-4d47-11eb-8f20-4a1eda9e5917.png)

**Comment by goliakshay357** [comment]
Thanks for raising this issue! :smiley:

**Comment by shivaamm** [comment]
Toolbox and Close option are half hidden behind the Canvasboard Beta section.

@goliakshay357 welcomee!
