### ISSUE TITLE
Add a GitHub action to auto-assign Mentors for every PR 

### ISSUE THREAD

**Issue by m-code12** [Canvasbird/canvasboard#315]
I would like to add a GitHub action to auto-assign mentors for every PR. It sometimes becomes hectic for the mentors to take a look at all the Projects for the PRs made by the Contributors. This action would give a nice notification about reviewing the pr and make things pretty easy for the mentor. It would automatically ask for reviews by the mentors on every pr created.

Demo :
<img src="https://user-images.githubusercontent.com/1641039/78471193-71573200-776a-11ea-9b40-810c2d63270e.png">

**Comment by kingavatar** [comment]
Thanks for the Suggestion. Would be really helpful.

**Comment by m-code12** [comment]
@kingavatar Whom should I add as the reviewers, @Kajol-Kumari , @goliakshay357 and you, right?

**Comment by goliakshay357** [comment]
Yes.

**Comment by goliakshay357** [comment]
Hey @m-code12,
Is this DWOC related? 

Thanks

**Comment by m-code12** [comment]
> Hey @m-code12,
> Is this DWOC related?
> 
> Thanks

No NWOC
