### ISSUE TITLE
Add a scroll-to-top button in the website

### ISSUE THREAD

**Issue by m-code12** [Canvasbird/canvasboard#318]
I would like to add a new feature to the website, a scroll-to-top button that will take the user to the top of the page when clicked on. This comes quite handy when the user reaches the end of the page and has to scroll way back to the top.

**Comment by m-code12** [comment]
@Kajol-Kumari @goliakshay357 Should I implement this?

**Comment by goliakshay357** [comment]
Sure! That would be great.

**Comment by m-code12** [comment]
@Kajol-Kumari Please assign me points for opening this issue.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Please assign me points for opening this issue.

Done :)

**Comment by neha-kothari** [comment]
Changes committed and pushed.
