### ISSUE TITLE
Spaces are allowed while entering workspace name

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#333]
**Describe the bug** 🐛 
When you create a new workspace in the dashboard. The name parameter is also accepting only spaces which is not efficient and right way to enter a name.

**To Reproduce**
 1. Go to Dashboard
 2. Click on "Add New Workspace"
 3. **Just enter spaces in name field**

**Observed behavior**
Only spaces are also getting accepted to name a file

**Expected behavior**
only spaces should not allowed

**Screenshots**
![image](https://user-images.githubusercontent.com/32712438/104766271-50f3e380-5790-11eb-8167-c87ea50ac444.png)

**Comment by Harshita-Kanal** [comment]
Can I take this up?

**Comment by goliakshay357** [comment]
Sure!

**Comment by goliakshay357** [comment]
Hey @Harshita-Kanal,
Working on this issue?

**Comment by vismitap** [comment]
Hey! I would like to work on this issue! Please guide me on how I can approach this problem?

**Comment by goliakshay357** [comment]
Hey @Vishal-raj-1,
Please feel free to checkout [this](https://zellwk.com/blog/check-empty-input-js/)

Thanks

**Comment by Kevan-Y** [comment]
Hi if it is still active, may I have try.

**Comment by goliakshay357** [comment]
Hello @Kevan-Y,
Sure!

**Comment by hemant8620** [comment]
Hey, Is this issue still active?
If this is active then I would like to work on this.

**Comment by goliakshay357** [comment]
Hello @hemant8620, 
This issue is currently been assigned to @Kevan-Y. 
@Kevan-Y would you like this solve this issue or pass it to @hemant8620 ?

**Comment by Kevan-Y** [comment]
@goliakshay357 , I would like to actually solve it

**Comment by Kevan-Y** [comment]
@goliakshay357, I notice the error handler in the front-end is not handled well, should we open another Issue and add some improvement in the front-end. Like a message in red below the input saying folder name should be required.
