### ISSUE TITLE
Change Beta font and fontsize

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#335]
**Is your feature request related to a problem? Please describe.**
Change the word "Beta" to different font and fontsize. ( because CB is **c**anvas**b**oard but not **c**anvasboard **b**eta)

**Comment by Harshita-Kanal** [comment]
Can I take this up?

**Comment by goliakshay357** [comment]
@Harshita-Kanal, Sure!

**Comment by goliakshay357** [comment]
Try out 
    `font-family: Harmattan,sans-serif;
`
