### ISSUE TITLE
Enhancement in Scroll to Top Button

### ISSUE THREAD

**Issue by Kajol-Kumari** [Canvasbird/canvasboard#368]
Deliverables:

- [ ] Make the cursor to pointer as soon as we hover on `scroll to top` icon
- [ ] We should have a nice hovering effect on the `scroll to top` icon (maybe color changing effect)

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue. Please assign me this issue.

**Comment by Kajol-Kumari** [comment]
Sure @sakshikhachane please go ahead with this issue
Happy learning :)

**Comment by sakshikhachane** [comment]
@Kajol-Kumari Is this looking better or should I change the hovering effects?

![Canvasboard - Google Chrome 01-02-2021 18_42_55 (2)](https://user-images.githubusercontent.com/53635792/106463519-8ea97980-64bd-11eb-8322-2830320e209e.png)

**Comment by Kajol-Kumari** [comment]
Hey @sakshikhachane please try changing the icon color instead of shadow effect
