### ISSUE TITLE
Enhancement in Welcome message on Dashbaoard

### ISSUE THREAD

**Issue by Kajol-Kumari** [Canvasbird/canvasboard#374]
Updated Deliverable:

Design Inspiration:
![image](https://user-images.githubusercontent.com/32712438/108738677-e33e9280-7559-11eb-9b7c-be431358ff69.png)

Current Welcome message
![Screenshot from 2021-02-02 12-47-27](https://user-images.githubusercontent.com/44888949/106565505-ef37c580-6554-11eb-9353-341887b4ecf0.png)

References and important links:

For Title: 
font: [Medium] https://fonts.google.com/specimen/Rubik?query=rub&preview.text_type=custom 

For Date 
font:[Regular] https://fonts.google.com/specimen/Rubik?query=rub&preview.text_type=custom

Please feel free to come up with your own custom designs or start building on top of this

**Comment by ShivangiRai1310** [comment]
Hi, would like to work on this issue under Dwoc & Swoc.

**Comment by Kajol-Kumari** [comment]
> Hi, would like to work on this issue under Dwoc & Swoc.

sure @ShivangiRai1310  :)
