### ISSUE TITLE
Horizontal Overflow

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#389]
**Describe the bug** 🐛 
Remove the horizontal overflow in all responsive screens

locations: 
https://canvasboard.live/login
https://canvasboard.live/sign-up

![bug](https://user-images.githubusercontent.com/32712438/109205329-73840e00-77cc-11eb-9214-89bf26ebabfe.gif)

**Comment by dollyjain51099** [comment]
I would like to work on this issue, @goliakshay357 kindly assign it to me!

**Comment by Aniket118** [comment]
I would like to work on this issue, @goliakshay357 kindly assign it to me!

**Comment by goliakshay357** [comment]
@Aniket118, You can work on #390 as you asked. 
Thanks

**Comment by dollyjain51099** [comment]
@goliakshay357 can u please add the label for swoc!
