### ISSUE TITLE
Automate public file creation for plugins

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#408]
A CLI interface to create plugins file.

**Comment by SEETHAMRAJU** [comment]
This issue sounds interesting. Could please elaborate more about it.

**Comment by goliakshay357** [comment]
Hey @SEETHAMRAJU, 

Generally for creating plugins on Canvasboard, we create .ts files in the /plugins directory. You can automate this process by creating a file with a plugin initial template. These steps can be done interactively with the custom CLI commands which run a shell script to insert a file in the /plugins directory.

Few general Information is needed before creating a file via CLI:
1. filename
2. Template type

Note: When you create a file the import has to be automated in the new_board component.

**Comment by SEETHAMRAJU** [comment]
Seems interesting. Can I work on this issue ?
