### ISSUE TITLE
Add a scroll bar in the right end

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#423]
**Is your feature request related to a problem? Please describe.**
Add a scroll bar in the right end to show the scrolling effect for better user experience.

![image](https://user-images.githubusercontent.com/32712438/135739500-1ec54511-424c-4dda-ad87-a28db4561744.png)

Location:  components/new-board

**Comment by wsameer** [comment]
Hey, i'd like to work on this issue.
