### ISSUE TITLE
Slides Wont show up few a times

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#428]
**Is your feature request related to a problem? Please describe.**
The Slides preview feature wont show up few a times. 

![image](https://user-images.githubusercontent.com/32712438/135757103-f7f7bbcc-c74c-4c92-8a16-9071f14cc56e.png)

**Comment by aguyran** [comment]
I think the issue was that Reveal was global and was not reinitializing the DOM with classes, if you changed page with back button. Gonna make PR for this.
