### ISSUE TITLE
Activate enter action after entering password during login

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#452]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/32712438/137094128-7d00e7c2-914e-4608-99ee-569361c1f9b7.png)

After entering the email and password after the login. By pressing the enter keyboard, no event gets triggered to have a successfull login. 

Activating the enter keyboard will make the user flow smooth.

**Comment by Dinoosawruss** [comment]
Hey, could I be assigned to this?

**Comment by goliakshay357** [comment]
Sure!
