### ISSUE TITLE
CSS Issue

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#453]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/32712438/137094497-c5525d22-d104-4281-b1f3-a393ada1ec7d.png)

Position the eye svg properly in signup page.

**Comment by infinityover** [comment]
Can i work on it?

**Comment by goliakshay357** [comment]
Hello @infinityover,
Sure!
