### ISSUE TITLE
Link verification 

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#471]
**Is your feature request related to a problem? Please describe.**
A link verification function before attaching the links to the embed plugin/youtube plugin

**Comment by patrikhv** [comment]
Hi, can you describe this issue more? I am interested in it.

**Comment by goliakshay357** [comment]
Hello @patrikhv,
When you paste a link in the embed plugin or youtube plugin. Verification/Validation of the link shud be taken care. 

Steps:
1. User pastes the link in the input field
2. When clicked on "ENTER", validate the link. 
3. if correct, move forward
4. if wrong due to some reason, log the error

Eg:
![image](https://user-images.githubusercontent.com/32712438/145680552-67d9e66c-e08a-46a1-89b0-052a65ce783c.png)

**Comment by patrikhv** [comment]
Thanks. Where is this component located?

**Comment by goliakshay357** [comment]
For Embed Plugin: https://github.com/Canvasbird/canvasboard/blob/f3f95fcb431d0dacab6f443279e8bfe9c2bc4231/src/app/components/new-board/new-board.component.html#L894

You can add the click function in ```.ts``` file and then make the logic for verification. 

For Youtube Plugin:
https://github.com/Canvasbird/canvasboard/blob/f3f95fcb431d0dacab6f443279e8bfe9c2bc4231/src/app/components/new-board/new-board.component.html#L968
The function is already there in the ```.ts``` file. 
So you can just add the verification function [here](https://github.com/Canvasbird/canvasboard/blob/f3f95fcb431d0dacab6f443279e8bfe9c2bc4231/src/app/components/new-board/new-board.component.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1143)

**Comment by Aniket-508** [comment]
Can we just use input type as url instead of text for embed link and write a simple custom regex for youtube validation? @goliakshay357

**Comment by goliakshay357** [comment]
Good point.
