### ISSUE TITLE
Footer in contribution page

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#50]
Fix footer in contribution page
![image](https://user-images.githubusercontent.com/32712438/94241971-00335300-ff33-11ea-9480-fea199814f18.png)

**Comment by CodeSarthak** [comment]
Hey @goliakshay357 👋

I'd like to try this one but I don't seem to understand what exactly needs to be fixed here.

**Comment by goliakshay357** [comment]
Hi @CodeSarthak , 
The position of footer should always be in the bottom. You could see that the footer in this component is not in the bottom. 

**Component**: contribution
**Path**: components/contribution
**redirect path**: /contribution

Thanks! :)

**Comment by goliakshay357** [comment]
You can clear out #75 at the same time by just adding the route-link.
Thanks!

**Comment by CodeSarthak** [comment]
It looks perfectly fine of my end. 

It might be an issue with the responsiveness.

![image](https://user-images.githubusercontent.com/24937677/94717123-7ee22300-036d-11eb-91d0-d5ee4de3a8dd.png)

**Comment by goliakshay357** [comment]
That's weird..
In which resolution is the screenshot taken?

In my laptop: (Resolution Mentioned in each photo)
![image](https://user-images.githubusercontent.com/32712438/94720279-e1d5b900-0371-11eb-9e05-8a6c4944684b.png)
![image](https://user-images.githubusercontent.com/32712438/94720413-1184c100-0372-11eb-81c4-1b023918ca1c.png)
![image](https://user-images.githubusercontent.com/32712438/94720492-2c573580-0372-11eb-94e9-7afebe69748b.png)

**Comment by CodeSarthak** [comment]
Ah, yes. I believe it a resolution-specific issue.

**Comment by goliakshay357** [comment]
@CodeSarthak are you working on this issue?
