### ISSUE TITLE
Show plugin name on hover in toolbox

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#61]

**Comment by geeks5551** [comment]
hey can I contribute to the advanced CSS styling like animation,transition ,translation ,flexbox,media query etc to make the issue more responsive?

**Comment by goliakshay357** [comment]
@geeks5551  Sure :+1:

**Comment by goliakshay357** [comment]
Curious to know your ideas and pipeline.

**Comment by geeks5551** [comment]
ya sure , so can you please assign me this issue

**Comment by goliakshay357** [comment]
Sure. 
Can you please join our IRC channel for further discussion? 
Link: https://gitter.im/canvasbird/canvasboard-frontend
Thanks

**Comment by geeks5551** [comment]
okk sure will do that

**Comment by geeks5551** [comment]
but please assign me with this issue first so that I can start with the work ?

**Comment by kingavatar** [comment]
Duplicate of #159
