### ISSUE TITLE
Cancel button for uploading a new image

### ISSUE THREAD

**Issue by Findingone** [Canvasbird/canvasboard#66]
When we click on button to upload an image, If we then click on cancel even then it is going ahead with confirming the url. It should hide the browser alert as soon as cancel is pressed. 

Steps to reproduce:
On any card, click on image to open a new image. then click on cancel.

**Comment by goliakshay357** [comment]
Hi @Findingone ,
Would be great if you can attach a supporting GIF for describing the issue.

**Comment by geeks5551** [comment]
hey can I make the button more responsive  with the help of box-model, box-sizing, animation, transition,translation, media query etc.?

**Comment by goliakshay357** [comment]
@geeks5551 Sure. You can do that. 
@Findingone Can you coordinate with @geeks5551  regarding your updates and ideas?
Thanks

**Comment by Findingone** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/54023582/94925389-c3400100-04dc-11eb-8bbe-c34a6cde9339.gif)
@goliakshay357 Here is the GIF for the problem.

**Comment by goliakshay357** [comment]
@Findingone Can you please join the IRC channel for further communication. 
Thanks

**Comment by goliakshay357** [comment]
Seems like you need to take the latest pull before working.

**Comment by Findingone** [comment]
> @Findingone Can you please join the IRC channel for further communication.
> Thanks

**Comment by Findingone** [comment]
yeah sure I'll join the channel
