### ISSUE TITLE
Adding features description on homepage

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#69]
Example template
![image](https://user-images.githubusercontent.com/32712438/94340086-94c5b000-001c-11eb-8f29-d7cc2c51f3b1.png)

**Comment by geeks5551** [comment]
hey, can I add features description on the homepage?

**Comment by goliakshay357** [comment]
@geeks5551 Yes sure. 
Can you join our gitter channel for further discussions on improvements. 

Thanks.
