### ISSUE TITLE
Add popular colors toolbox

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#7]
Adding popular colors used toolbox for easy handling.

**Comment by pallavithakare28** [comment]
@goliakshay357 @deepak2431 I would like to work on this issue.

**Comment by deepak2431** [comment]
@pallavithakare28 Go ahead! Let us know if you need any clarification.

**Comment by pallavithakare28** [comment]
@deepak2431  Thank you for assigning. Can you please help out? I am not getting from where I have to start. And from where I have to make changes.

**Comment by goliakshay357** [comment]
Hey @pallavithakare28 , 
You could start working on this issue in board component (path: src/app/components/board)
The required tools and functions are added in the above component mentioned. 

You could even reach out to other members of the team in the gitter channel (mentioned in the README).
Hope that helps. 
Thanks

**Comment by pallavithakare28** [comment]
@goliakshay357 Thank you for the help.

**Comment by goliakshay357** [comment]
@pallavithakare28, the following variable is responsible for changing colour of the pen. By clicking the frequently used colour boxes, the value of this variable changes.

``` typescript  
  //tools
  penColour:any;
```

Thanks.

**Comment by alinebrito** [comment]
Hi @goliakshay357 , can I get this issue?

**Comment by goliakshay357** [comment]
sure :+1:
