### ISSUE TITLE
Center Logo and Adjust contents in mobile resolution

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#72]
Center Logo in Screen Resolution lesser than iPad.
![image](https://user-images.githubusercontent.com/32712438/94340559-6fd33c00-0020-11eb-8134-77a9e73f4a4d.png)

**Comment by CodeSarthak** [comment]
Hey @goliakshay357 , I'd like to take up this issue!

**Comment by deepak2431** [comment]
@CodeSarthak Sure, go ahead!

**Comment by CodeSarthak** [comment]
@goliakshay357 , it already appears to be centered. 

![image](https://user-images.githubusercontent.com/24937677/94717502-0b8ce100-036e-11eb-8bf4-b33c2fbdd1af.png)

**Comment by goliakshay357** [comment]
@CodeSarthak Thanks for the notice. Good to know that this issue seems solved. But the content area doesn't seem responsive. Maybe you could work on that. 
![image](https://user-images.githubusercontent.com/32712438/94721905-25312700-0374-11eb-8af3-995870fca686.png)

Thanks

**Comment by deepak2431** [comment]
@CodeSarthak Also please check once if it's not responsive for any other resolution? Make sure everything is completely responsive logo, nav-bar, header for this issue.
