### ISSUE TITLE
UI Fixes in home page

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#73]
UI Fixes in home page
Resolution: Mobile

![image](https://user-images.githubusercontent.com/32712438/94340603-ca6c9800-0020-11eb-9b0b-15e7350307fe.png)

**Comment by joshyide** [comment]
Hi there @goliakshay357 !
I'd like to take on this issue for hacktoberfest if you wanna assign it to me? :octocat: 😄

**Comment by goliakshay357** [comment]
@joshyide Sure :+1:
