### ISSUE TITLE
UI Fixes in Footer

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#74]
UI Fixes in Footer
Resolution: Mobile
![image](https://user-images.githubusercontent.com/32712438/94340645-1c152280-0021-11eb-8bb8-5a2fd46bde24.png)

**Comment by rebelchris** [comment]
@goliakshay357 I can take this issue if that's ok with you 🤟

**Comment by goliakshay357** [comment]
@rebelchris sure! :+1:
