### ISSUE TITLE
Redirect Contribute button to canvasboard github page.

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#75]
Link: https://github.com/Canvasbird/canvasboard/
Component: HomeComponent
Redirect: /home
path: components/home

![image](https://user-images.githubusercontent.com/32712438/94341330-153cde80-0026-11eb-85d7-adde89522114.png)

**Comment by geeks5551** [comment]
hey can i contribute towards redirecting the Contribute button to canvasboard github page.
