### ISSUE TITLE
Adding Eraser.

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#82]
Adding Eraser  functionality to canvas board.
![image](https://user-images.githubusercontent.com/32712438/94374807-5d462900-012c-11eb-9ddb-f0726e110c2d.png)

path: /board
Component: board

**Comment by alinebrito** [comment]
Hi, can I get this issue?

**Comment by goliakshay357** [comment]
@alinebrito Sure :+1:
