### ISSUE TITLE
Adjust the Highlighter pen opacity

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#84]
Adjusting the Highlighter pen opacity so the content highlighted can be viewed properly.

![image](https://user-images.githubusercontent.com/32712438/94374865-ecebd780-012c-11eb-87ac-c630703feb35.png)

path: /board
Component: board

**Comment by lucassorenson** [comment]
Can I try this out?

**Comment by goliakshay357** [comment]
@lucassorenson Sure :+1:

**Comment by goliakshay357** [comment]
hey @lucassorenson, 
Are you working on this issue?
