### ISSUE TITLE
Need help In NODEJS

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#91]
- [ ] File structure management in db.
- [ ] AUTH using passport.js
- [ ] Saving notes and shareable unique link to view notes.

**Comment by AyonPal** [comment]
Looks interesting. Want to work on it

**Comment by goliakshay357** [comment]
@AyonPal Thanks for your interest. Can you please join our IRC channel for further discussion?
Link: https://gitter.im/canvasbird/canvasboard-frontend
Thanks
