### ISSUE TITLE
Adjusting Eraser size. 

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#95]
Buttons to Change the eraser size as per the requirements.

**Comment by alinebrito** [comment]
Hi @goliakshay357, can I get this issue too? (I worked on issue #82)

**Comment by goliakshay357** [comment]
Sure :+1:

**Comment by goliakshay357** [comment]
You could add different size boxes in the toolbar
Thanks

**Comment by goliakshay357** [comment]
Can you please join our gitter channel for further communications.
Link: https://gitter.im/canvasbird/canvasboard-frontend
Thanks
