### ISSUE TITLE
Fix Home screen CSS issue in mobile

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#97]
![image](https://user-images.githubusercontent.com/32712438/94915275-3724de00-04ca-11eb-88e9-fc9c78fe8692.png)
Component: home
path: components/home
redirect: /home

**Comment by IzacVrushabh** [comment]
I would love to work on it , can you assigned to me ?

**Comment by goliakshay357** [comment]
Sure @IzacVrushabh :+1:

**Comment by goliakshay357** [comment]
Please feel free to shoot out your ideas and artwork in the IRC channel mentioned in the README.md
At the same time... please feel free to checkout Issue #69  and #88

Thanks

**Comment by IzacVrushabh** [comment]
> Please feel free to shoot out your ideas and artwork in the IRC channel mentioned.
> At the same time... please feel free to checkout Issue #69 and #88
> 
> Thanks

I am working on this responsive part , Can you share the link of IRC channel , so that I can share my ideas . I have some amazing ideas.

**Comment by goliakshay357** [comment]
That sounds Interesting! 
Curious to know your ideas and artwork. 
Link:https://gitter.im/canvasbird/canvasboard-frontend

Thanks

**Comment by IzacVrushabh** [comment]
Hey , I found that #97 and #73  , both are same issue ,you also assigned someone for #73 issue , so I'm un-assigning myself . 
Thankyou.

**Comment by goliakshay357** [comment]
We are sorry for the duplicates. But #73 is closed. 
You can maybe work on #104 and #50 on the contribution page

Suggestions and Improvements are highly appreciated in open source. Please feel free to start a conversation in our IRC channel.
